.TH ws_extend 1 "March 2013" "USER COMMANDS"

.SH NAME
ws_extend \- extend a workspace

.SH SYNOPSIS
.B ws_extend WORKSPACE DAYS

.SH DESCRIPTION
Extend a 
.B
workspace 
to last until DAYS in the future.
This is a convenience wrapper around 
.B
ws_allocate -x


.SH AUTHOR
Written by Holger Berger

.SH SEE ALSO
ws_allocate, ws_release, ws_list, ws_restore
